"""Supervisor Agent - reviews agent outputs, requests refinement, ensures quality.

Implements the Supervisor pattern (2026 best practice):
- Reviews merged agent responses
- Can request re-generation if quality is insufficient
- Synthesizes multi-agent outputs into coherent response
- Applies reflection/self-critique before returning to user
"""

import os
import json
import logging
from langchain_openai import AzureChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from agents import AgentState

_llm = None
MAX_REFINEMENT_LOOPS = 2


def _get_llm():
    global _llm
    if _llm is None:
        _llm = AzureChatOpenAI(
            azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
            api_key=os.environ["AZURE_OPENAI_KEY"],
            azure_deployment=os.environ["AZURE_OPENAI_CHAT_DEPLOYMENT"],
            api_version="2024-06-01",
            temperature=0.1, max_tokens=4096,
        )
    return _llm


SUPERVISOR_PROMPT = ChatPromptTemplate.from_template(
    "You are a Supervisor Agent for a call centre AI platform. Your role is to:\n"
    "1. Review the response generated by specialist agents\n"
    "2. Ensure it fully answers the user's question\n"
    "3. Synthesize multiple agent outputs into a coherent, actionable response\n"
    "4. Flag if the response needs improvement\n\n"
    "User question: {question}\n"
    "Agents used: {agents}\n"
    "Agent response:\n{response}\n\n"
    "EVALUATE and respond with JSON:\n"
    '{{"verdict": "APPROVE|REFINE", "refined_response": "<improved response if REFINE, otherwise empty>", '
    '"reasoning": "<why you approved or what you improved>", '
    '"quality_score": <1-5>, "completeness": <1-5>, "actionability": <1-5>}}'
)


REFLECTION_PROMPT = ChatPromptTemplate.from_template(
    "You are performing self-critique on an AI response for a call centre platform.\n\n"
    "Original question: {question}\n"
    "Response to evaluate:\n{response}\n\n"
    "Self-critique checklist:\n"
    "1. Does it directly answer what was asked? (not tangential)\n"
    "2. Are all claims supported by data or clearly marked as estimates?\n"
    "3. Are there actionable next steps?\n"
    "4. Is it concise without losing important details?\n"
    "5. Would a call centre supervisor find this immediately useful?\n\n"
    "If ALL checks pass, respond: PASS\n"
    "If any check fails, respond with an improved version that fixes the issues.\n\n"
    "Response (PASS or improved version):"
)


def supervise(state: AgentState) -> AgentState:
    """Supervisor reviews and optionally refines the merged response."""
    response = state.get("response", "")
    question = state.get("raw_question", state.get("question", ""))
    routes = state.get("routes", [])

    if not response:
        return state

    # Step 1: Supervisor review
    try:
        result = (SUPERVISOR_PROMPT | _get_llm()).invoke({
            "question": question[:500],
            "agents": ", ".join(routes),
            "response": response[:3000],
        })

        parsed = json.loads(result.content)
        verdict = parsed.get("verdict", "APPROVE")
        refined = parsed.get("refined_response", "")
        reasoning = parsed.get("reasoning", "")

        logging.info(f"[SUPERVISOR] verdict={verdict}, reasoning={reasoning[:80]}")

        if verdict == "REFINE" and refined:
            response = refined

    except Exception as e:
        logging.warning(f"[SUPERVISOR] Review failed: {e}")

    # Step 2: Reflection/Self-Critique
    response = _reflect(question, response)

    return {**state, "response": response}


def _reflect(question: str, response: str) -> str:
    """Self-critique loop - checks if response meets quality bar."""
    try:
        result = (REFLECTION_PROMPT | _get_llm()).invoke({
            "question": question[:500],
            "response": response[:3000],
        })

        critique = result.content.strip()

        if critique.upper().startswith("PASS"):
            logging.info("[REFLECTION] PASS - response approved")
            return response
        else:
            logging.info("[REFLECTION] Refined response generated")
            return critique

    except Exception as e:
        logging.warning(f"[REFLECTION] Failed: {e}")
        return response
